# Generated by Django 5.1.1 on 2024-12-06 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo_atendimento', models.CharField(max_length=50)),
                ('descricao_abertura', models.TextField()),
                ('A_tipo_atendimento', models.CharField(max_length=50)),
                ('usuario_abertura', models.CharField(max_length=100)),
                ('usuario_responsavel', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('cliente_nome', models.CharField(max_length=255)),
                ('cliente_codigo', models.IntegerField()),
                ('servico_id', models.IntegerField()),
                ('servico_nome', models.CharField(max_length=255)),
                ('data_cadastro', models.DateTimeField()),
                ('data_fechamento', models.DateTimeField(blank=True, null=True)),
                ('id_atendimento', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Trecho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf_a', models.CharField(max_length=2, verbose_name='UF - A')),
                ('municipio_a', models.CharField(max_length=100, verbose_name='Município - A')),
                ('nome_pop_a', models.CharField(max_length=100, verbose_name='Nome do POP - A')),
                ('trecho', models.CharField(max_length=255, verbose_name='Trecho')),
                ('uf_b', models.CharField(max_length=2, verbose_name='UF - B')),
                ('municipio_b', models.CharField(max_length=100, verbose_name='Município - B')),
                ('nome_pop_b', models.CharField(max_length=100, verbose_name='Nome do POP - B')),
                ('tipo_rede', models.CharField(max_length=100, verbose_name='Tipo de Rede')),
                ('responsaveis', models.CharField(max_length=255, verbose_name='Responsáveis')),
                ('equipamento_a', models.CharField(default='', max_length=100, verbose_name='Equipamento - A')),
                ('porta_a', models.CharField(default='', max_length=100, verbose_name='Porta Equipamento - A')),
                ('equipamento_b', models.CharField(default='', max_length=100, verbose_name='Equipamento - B')),
                ('porta_b', models.CharField(default='', max_length=100, verbose_name='Porta Equipamento - B')),
            ],
        ),
        migrations.CreateModel(
            name='Protocolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_rede', models.CharField(choices=[('METRO', 'Rede Metro'), ('DWDM', 'Rede DWDM'), ('CAPACIDADE', 'Capacidade')], max_length=100)),
                ('numero_chamado_interno', models.CharField(default='AUTOMATICO', max_length=50)),
                ('estado', models.CharField(max_length=2)),
                ('nome_pop_a', models.CharField(max_length=100)),
                ('nome_pop_b', models.CharField(max_length=100)),
                ('nome_responsavel', models.CharField(default='Megalink', max_length=100)),
                ('numero_chamado_os', models.CharField(max_length=50)),
                ('tipo_evento', models.CharField(choices=[('RUPTURA', 'Ruptura'), ('ATENUAÇÃO', 'Atenuação'), ('INDISPONIBILIDADE', 'Indisponibilidade'), ('TAXA DE ERRO', 'Taxa de Erro'), ('OSCILAÇÃO', 'Oscilação'), ('FALHA ELÉTRICA', 'Falha Elétrica'), ('OUTRAS', 'Outros')], max_length=20)),
                ('site_a', models.CharField(max_length=100)),
                ('equipamento_site_a', models.CharField(max_length=100)),
                ('porta_site_a', models.CharField(max_length=50)),
                ('site_b', models.CharField(max_length=100)),
                ('equipamento_site_b', models.CharField(max_length=100)),
                ('porta_site_b', models.CharField(max_length=50)),
                ('data_hora_falha', models.DateTimeField()),
                ('responsavel_trecho', models.CharField(max_length=100)),
                ('protocolo_parceiro', models.CharField(max_length=100)),
                ('clientes_afetados', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.CharField(editable=False, max_length=255)),
                ('tipo_atendimento', models.IntegerField(choices=[(661, 'NOC TX > ATENUAÇÃO PARCEIRO'), (662, 'NOC TX > OSCILAÇÃO PARCEIRO'), (663, 'NOC TX > PT NOC - CLIENTE'), (664, 'NOC TX > RUPTURA PARCEIRO'), (666, 'NOC TX > ATENUAÇÃO MEGALINK'), (668, 'NOC TX > OSCILAÇÃO MEGALINK'), (723, 'NOC TX > ENERGIA'), (660, 'NOC TX'), (667, 'NOC TX > INDISPONIBILIDADE SITE'), (670, 'NOC TX > REBOOT SITE'), (669, 'NOC TX > OUTROS'), (671, 'NOC TX > RUPTURA MEGALINK')], default=660, help_text='Selecione o tipo de atendimento com base nos IDs disponíveis', verbose_name='Tipo de Atendimento')),
                ('ativo', models.BooleanField(default=True)),
                ('atendimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='protocolocd.atendimento')),
                ('trecho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protocolocd.trecho', verbose_name='Trecho')),
            ],
        ),
    ]
