# Generated by Django 5.1.1 on 2024-12-10 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolocd', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='protocolo',
            options={'ordering': ['trecho']},
        ),
        migrations.AlterModelOptions(
            name='trecho',
            options={'ordering': ['trecho']},
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('mensagem', models.TextField()),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='protocolocd.atendimento')),
            ],
        ),
    ]
