# Generated by Django 5.1.1 on 2025-03-10 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolocd', '0002_alter_protocolo_options_alter_trecho_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescricaoTrecho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição do Trecho')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('trecho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descricoes', to='protocolocd.trecho')),
            ],
            options={
                'verbose_name': 'Descrição do Trecho',
                'verbose_name_plural': 'Descrições dos Trechos',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
