# Generated by Django 5.1.5 on 2025-04-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolocd', '0004_servico_protocolo_pop_trecho'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolo',
            name='status_atendimento',
            field=models.CharField(choices=[('PENDENTE (Abertura de OS)', 'PENDENTE (Abertura de OS)'), ('AGUARDANDO ANALISE', 'AGUARDANDO ANALISE')], default='PENDENTE (Abertura de OS)', max_length=100),
        ),
    ]
