# Generated by Django 5.1.5 on 2025-04-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolocd', '0005_protocolo_status_atendimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolo',
            name='status_atendimento',
            field=models.IntegerField(choices=[(1, 'PENDENTE (Abertura de OS)'), (2, 'AGUARDANDO ANALISE')], default=2),
        ),
    ]
