# Generated by Django 5.1.5 on 2025-04-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolocd', '0007_responsavel_protocolo_responsavel_atendimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsavel',
            name='id_hubsoft',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID Hubsoft'),
        ),
    ]
