# Generated by Django 5.1.5 on 2025-04-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolocd', '0008_responsavel_id_hubsoft'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ordem_servico', models.IntegerField(unique=True)),
                ('id_atendimento', models.IntegerField()),
                ('tipo_ordem_servico', models.CharField(max_length=100)),
                ('numero_ordem_servico', models.CharField(max_length=100)),
                ('descricao_abertura', models.TextField()),
                ('status', models.CharField(choices=[('aguardando_agendamento', 'Aguardando Agendamento'), ('agendado', 'Agendado'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], max_length=50)),
                ('data_cadastro', models.DateTimeField()),
                ('data_inicio_programado', models.DateTimeField()),
                ('data_termino_programado', models.DateTimeField()),
                ('cliente_servico_display', models.CharField(max_length=255)),
                ('cliente_servico_id', models.IntegerField()),
                ('cliente', models.CharField(max_length=255)),
                ('response_status', models.CharField(max_length=50)),
                ('response_msg', models.CharField(max_length=255)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
