# Generated by Django 5.1.5 on 2025-04-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolocd', '0010_alter_servico_table_suporteprotocolo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suporteprotocolo',
            name='data_hora_falha',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suporteprotocolo',
            name='id_tipo_atendimento',
            field=models.IntegerField(choices=[(0, 'TIPO DE ATENDIMENTO'), (0, 'TIPO DE ATENDIMENTO'), (0, 'TIPO DE ATENDIMENTO'), (0, 'TIPO DE ATENDIMENTO'), (0, 'TIPO DE ATENDIMENTO')]),
        ),
    ]
