# Generated by Django 5.1.5 on 2025-04-24 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolocd', '0011_suporteprotocolo_data_hora_falha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suporteprotocolo',
            name='atendimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='protocolocd.atendimento'),
        ),
        migrations.AlterField(
            model_name='suporteprotocolo',
            name='id_atendimento_status',
            field=models.IntegerField(choices=[(1, 'PENDENTE (Abertura de OS)'), (2, 'AGUARDANDO ANALISE'), (22, 'EM ANDAMENTO')]),
        ),
        migrations.AlterField(
            model_name='suporteprotocolo',
            name='id_tipo_atendimento',
            field=models.IntegerField(choices=[(688, 'ATACADO > LENTIDÃO/PROBLEMA GENERALIZADO'), (686, 'ATACADO > SWAP'), (632, 'ATACADO > SEM SERVIÇO'), (626, 'ATACADO > SOLICITAÇÃO DE CLIENTE'), (625, 'ATACADO > MANUTENÇÃO PREVENTIVA/CORRETIVA')]),
        ),
    ]
