# Generated by Django 5.1.5 on 2025-04-24 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocolocd', '0012_suporteprotocolo_atendimento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suporteprotocolo',
            old_name='atendimento',
            new_name='atendimento_suporte_id',
        ),
    ]
