# Generated by Django 5.1.5 on 2025-04-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolocd', '0013_rename_atendimento_suporteprotocolo_atendimento_suporte_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='suporteprotocolo',
            name='protocolo_atendimento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
