# Generated by Django 5.1.5 on 2025-04-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolocd', '0014_suporteprotocolo_protocolo_atendimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='cliente',
            field=models.CharField(max_length=755),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='cliente_servico_display',
            field=models.CharField(max_length=755),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='response_msg',
            field=models.CharField(max_length=755),
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='status_atendimento',
            field=models.IntegerField(choices=[(1, 'PENDENTE (Abertura de OS)'), (2, 'AGUARDANDO ANALISE')], default=2, verbose_name='Status do Atendimento'),
        ),
    ]
